# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false
r_build_args: --no-build-vignettes
r_check_args: --no-manual --timings
r:
  - release
  - devel
os:
  - linux
  - osx
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); covr::codecov()'
